name: Docker DevSecOps

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Build Docker Image
        run: |
          docker build -t docker-devsecops-lab:latest .
          
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker-devsecops-lab:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
