name: Docker DevSecOps

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  docker-security:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
              - name: Build Docker Image
        run: |
          docker build -t docker-devsecops-lab:latest .
